# https://grafana.github.io/grafana-operator/docs/examples/datasource_variables/readme/
# https://docs.redhat.com/en/documentation/openshift_container_platform/4.21/html/nodes/working-with-pods#nodes-pods-secrets-creating-sa_nodes-pods-secrets
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    kubernetes.io/service-account.name: "grafana-sa"
type: kubernetes.io/service-account-token
