{
 "title": "Infrastructure Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Alerts Dashboard", "type": "alertlist", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 } },
  {
   "title": "Compute Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (kube_node_labels{label_node_role_kubernetes_io_compute=\"true\"})"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum (kube_node_labels)" }
   ]
  },
  {
   "title": "Application Projects",
   "type": "singlestat",
   "description": "Excludes infrastructure namespaces",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_namespace_created{namespace!~\"(default|kube|openshift).*\"})"
    }
   ]
  },
  {
   "title": "Total Projects",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kube_namespace_created)" }
   ]
  },
  {
   "title": "Node State",
   "type": "graph",
   "description": "Detect NotReady, DiskPressure, MemoryPressure, PIDPressure, and OutOfDisk conditions on kubelet for Schedulable nodes",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (node) (kube_node_status_condition{condition=\"Ready\", status!=\"true\"}) and sum by (node) (kube_node_spec_unschedulable == 0))",
     "legendFormat": "NotReady: {{node}}"
    },
    {
     "expr": "(sum by (node) (kube_node_status_condition{condition=\"DiskPressure\", status=\"true\"}) and sum by (node) (kube_node_spec_unschedulable == 0))",
     "legendFormat": "DiskPressure: {{node}}"
    },
    {
     "expr": "(sum by (node) (kube_node_status_condition{condition=\"MemoryPressure\", status=\"true\"}) and sum by (node) (kube_node_spec_unschedulable == 0))",
     "legendFormat": "MemoryPressure: {{node}}"
    },
    {
     "expr": "(sum by (node) (kube_node_status_condition{condition=\"PIDPressure\", status=\"true\"}) and sum by (node) (kube_node_spec_unschedulable == 0))",
     "legendFormat": "PIDPressure: {{node}}"
    },
    {
     "expr": "(sum by (node) (kube_node_status_condition{condition=\"OutOfDisk\", status=\"true\"}) and sum by (node) (kube_node_spec_unschedulable == 0))",
     "legendFormat": "OutOfDisk: {{node}}"
    }
   ]
  },
  {
   "title": "Allocatable Cores",
   "type": "singlestat",
   "description": "Compute nodes only",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (kube_node_labels{label_node_role_kubernetes_io_compute=\"true\"} * on(node) group_left() kube_node_status_capacity_cpu_cores)"
    }
   ]
  },
  {
   "title": "Total Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (kube_node_labels * on(node) group_left() kube_node_status_capacity_cpu_cores)"
    }
   ]
  },
  {
   "title": "Application Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"true\",namespace!~\"(default|kube|openshift).*\"})"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"true\"})"
    }
   ]
  },
  {
   "title": "Allocatable Memory",
   "type": "singlestat",
   "description": "Compute nodes only",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (kube_node_labels{label_node_role_kubernetes_io_compute=\"true\"} * on(node) group_left() kube_node_status_capacity_memory_bytes)"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (kube_node_labels * on(node) group_left() kube_node_status_capacity_memory_bytes)"
    }
   ]
  },
  {
   "title": "Used App Storage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes {namespace!~\"(default|kube|openshift).*\"})/1e+9"
    }
   ]
  },
  {
   "title": "Allocatable App Storage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes {namespace!~\"(default|kube|openshift).*\"})/1e+9"
    }
   ]
  },
  { "title": "Node Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Utilization by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(1 - avg by(node) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[1m])* on(namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:))* count  by(node) (sum by(node, cpu) (node_cpu_seconds_total{job=\"node-exporter\"}  * on(namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:)) /scalar(sum(count  by(node) (sum by(node, cpu) (node_cpu_seconds_total{job=\"node-exporter\"}  * on(namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:))))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Infra Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum by (namespace) (sum by(namespace) (rate(container_cpu_usage_seconds_total{container_name!=\"\",container_name!=\"POD\",namespace=~\"(default|kube|openshift).*\"}[5m]))))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Usage by App Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum by (namespace) (sum by(namespace) (rate(container_cpu_usage_seconds_total{container_name!=\"\",container_name!=\"POD\",namespace!~\"(default|kube|openshift).*\"}[5m]))))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Utilization by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((sum by(node) (node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(namespace,\n  pod) group_left(node) node_namespace_pod:kube_pod_info:))\n- (sum by(node) ((node_memory_MemFree_bytes{job=\"node-exporter\"} + node_memory_Cached_bytes{job=\"node-exporter\"}\n  + node_memory_Buffers_bytes{job=\"node-exporter\"}) * on(namespace, pod) group_left(node)\n  node_namespace_pod:kube_pod_info:))) /\n((sum by(node) (node_memory_MemTotal_bytes{job=\"node-exporter\"} * on(namespace,\n  pod) group_left(node) node_namespace_pod:kube_pod_info:)))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Infra Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum by (namespace) (sum by(namespace) (container_memory_usage_bytes{container_name!=\"\",namespace=~\"(default|kube|openshift).*\"})))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage by App Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum by (namespace) (sum by(namespace) (container_memory_usage_bytes{container_name!=\"\",namespace!~\"(default|kube|openshift).*\"})))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Network Utilization by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (node) ((irate(node_network_receive_bytes_total{job=\"node-exporter\",device!~\"veth.+\"}[1m])) * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:)",
     "legendFormat": "in: {{node}}"
    },
    {
     "expr": "sum by (node) ((irate(node_network_transmit_bytes_total{job=\"node-exporter\",device!~\"veth.+\"}[1m])) * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:)",
     "legendFormat": "out : {{node}}"
    }
   ]
  },
  {
   "title": "Dropped Bytes by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum\n  by(node) ((irate(node_network_receive_drop_total{device!~\"veth.+\",job=\"node-exporter\"}[1m])\n  + irate(node_network_transmit_drop_total{device!~\"veth.+\",job=\"node-exporter\"}[1m]))\n  * on(namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization",
   "type": "graph",
   "description": "Display busiest device (highest I/O) for each server",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (irate(node_disk_io_time_seconds_total{job=\"node-exporter\",device=~\"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+\"}[1m]) * on (namespace, pod) group_left(node) node_namespace_pod:kube_pod_info:)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}